name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      uses: ./.github/actions/install
    - name: Lint
      uses: ./.github/actions/lint
    - name: Unit Test
      uses: ./.github/actions/unit-test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
