name: ObserveCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    - name: 'Setup Project Dependencies'
      run: ./bin/install.sh
    - name: 'Linting'
      run: ./bin/lint.sh
    - name: 'Unit Tests'
      run: ./bin/unit-test.sh
